#!/usr/bin/env python3

# MIT License
#
# Copyright (c) 2020 Markus Prasser
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

"""
IBHArchiver is a simple tool for creating personal archives of I'll Be Honest
"""

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk # pylint: disable=C0413

class MainWindow(Gtk.ApplicationWindow):
    """
    The main window (and class) (indirectly) containing all functionality
    """
    def __init__(self, win_title):
        super().__init__(title=win_title)

        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.add(main_box)

        # Filters
        filter_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        main_box.pack_start(filter_box, True, True, 0)

        # Items display
        display_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        tree_view = Gtk.TreeView()
        display_box.pack_start(tree_view, True, True, 0)
        main_box.pack_start(display_box, True, True, 0)

        # Buttons
        buttons_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        add_button = Gtk.Button.new_with_label('Add')
        buttons_box.pack_start(add_button, True, True, 0)
        play_button = Gtk.Button.new_with_label('Play')
        buttons_box.pack_start(play_button, True, True, 0)
        export_button = Gtk.Button.new_with_label('Export')
        buttons_box.pack_start(export_button, True, True, 0)
        main_box.pack_start(buttons_box, True, True, 0)

def main():
    """
    This is the entry point of IBHArchiver
    """
    main_win = MainWindow('IBHArchiver')
    main_win.show_all()
    main_win.connect('destroy', Gtk.main_quit)
    Gtk.main()

if __name__ == '__main__':
    main()
